
all:
	g++   -fpermissive -g -o main   -I../limlog/  ../limlog/*.cpp  io_hook.cpp rector_epoll.cpp coroutine.cpp base_thread.cpp work_thread.cpp work_test.cpp -std=c++11 -ldl -lpthread
clean:
	rm -rf *.o	main
